#name: snek
#on:
#  push:
#    branches:
#      - 'main'
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: KikimoraGames/itch-publish@v0.0.3
#        with: 
#          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
#          gameData: .
#          itchUsername: deathqrow
#          itchGameId: snek-rpg
#          buildChannel: html